### ISSUE TITLE
SSL certificate is invalid while downloading artifacts 

### ISSUE THREAD

**Issue by coolsan24** [MangoAutomation/BACnet4J#86]

**Comment by splatch** [comment]
@kubeliv hey, I think you're part of MangoAutomation/Radix team. Could you please forward this issue to someone who is entitled to manage your nexus instance? Its SSL certificate is expired since yesterday.

**Comment by kubeliv** [comment]
@splatch Apologies on this. I've been meaning to fix this, the process has been quite manual for some time, just haven't haven't had the time to do so. It has been renewed for the time being.
